#========lingx.com========
#Fri Mar 13 20:05:15 GMT+08:00 2026
tracseek.port2=8802
tracseek.database.username=root
tracseek.port1=8808
tracseek.database.ip=127.0.0.1
tracseek.database.password=
tracseek.database.port=3306
