package com.lingx.jt808.api.common;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import com.alibaba.fastjson.JSON;
import com.lingx.jt808.core.cmd.Cmd8104;
import com.lingx.jt808.core.service.JT808CommandService;
import com.lingx.jt808.core.utils.Utils;
import com.lingx.utils.TokenUtils;
import com.lingx.web.api.IApi;
import com.lingx.web.api.impl.AbstractAuthApi;
@Component
public class Api1172 extends AbstractAuthApi{
	@Autowired
	private JT808CommandService commandService;
	@Autowired
	private JdbcTemplate jdbcTemplate;
	@Override
	public int getApiCode() {
		return 1172;
	}

	public boolean isLog() {
		return false;
	}
	@Override
	public String getApiName() {
		return "查询全部参数";
	}
	@Override
	public String getGroupName() {
		return "车载监控";
	}
	@Override
	public Map<String, Object> api(Map<String, Object> params) {
		Map<String,Object> ret=IApi.getRetMap(1, "SUCCESS");
		if(this.checkIsNull(params, "deviceId",ret))return ret; 
		String carid=this.getParamString(params, "deviceId", "");
		String tid=this.commandService.getTidByCarid(carid);
		Cmd8104 cmd=new Cmd8104(tid);
		String token=IApi.getParamString(params, "lingxtoken", "");
		String userid=TokenUtils.getTokenData(token).getUserId();
		Map<String,Object> map=this.commandService.sendCommand(cmd, carid, userid, false);
		List<Map<String,Object>> list=this.jdbcTemplate.queryForList("select * from tgps_jt808_param order by id asc");
		ret.put("data", getList(map,list));
		return ret;
	}
	
	
	private  List<Map<String,Object>> getList(Map<String,Object> map,List<Map<String,Object>> list){
		List<Map<String,Object>> listRet=new ArrayList<>();
		for(Map<String,Object> m:list) {
			Object val=map.get(String.valueOf(Integer.parseInt(m.get("paramid").toString().substring(2), 16)));
			if(val!=null) {
				val=getValue(m.get("type").toString(),val);
				if("0".equals(val.toString()))continue;
				m.put("value", val);
				listRet.add(m);
			}
		}
		return listRet;
	}
	private  Object getValue(String type,Object value) {
		Object val=null;
		switch(type) {
		case "BYTE":
		case "WORD":
		case "DWORD":
			String temp=value.toString();
			byte[] bytes=Utils.hexToBytes(temp);
			val=Utils.byteArrayToInt(bytes);
			break;
		case "STRING":
			String temp1=value.toString();
			byte[] bytes1=Utils.hexToBytes(temp1);
			//ret.put("value",new String(bytes1));
			try {
				val=new String(bytes1,"GBK");
			} catch (Exception e) {
				val=new String(bytes1);
			}
			break;
		default:
			val=value;
		}
		
		return val;
	}
	public static String getMapString() {
		return "{\r\n"
				+ "        \"44\": \"00000003\",\r\n"
				+ "        \"88\": \"00015180\",\r\n"
				+ "        \"45\": \"00000003\",\r\n"
				+ "        \"89\": \"000004B0\",\r\n"
				+ "        \"46\": \"00000003\",\r\n"
				+ "        \"47\": \"00000003\",\r\n"
				+ "        \"48\": \"0000000F\",\r\n"
				+ "        \"49\": \"0003\",\r\n"
				+ "        \"272\": \"0000000000000000\",\r\n"
				+ "        \"273\": \"0000000000000000\",\r\n"
				+ "        \"112\": \"00000002\",\r\n"
				+ "        \"113\": \"00000080\",\r\n"
				+ "        \"114\": \"00000040\",\r\n"
				+ "        \"115\": \"00000040\",\r\n"
				+ "        \"116\": \"00000080\",\r\n"
				+ "        \"90\": \"00015180\",\r\n"
				+ "        \"117\": \"000600140000000000000500000000000000000701\",\r\n"
				+ "        \"91\": \"FF38\",\r\n"
				+ "        \"118\": \"04000001010000020200000303000004040000\",\r\n"
				+ "        \"92\": \"0708\",\r\n"
				+ "        \"119\": \"04010006001400000000000005000000000000000007020006001400000000000005000000000000000007030006001400000000000005000000000000000007040006001400000000000005000000000000000007\",\r\n"
				+ "        \"93\": \"0014\",\r\n"
				+ "        \"94\": \"00C8\",\r\n"
				+ "        \"16\": \"43544C5445\",\r\n"
				+ "        \"17\": \"63617264\",\r\n"
				+ "        \"18\": \"63617264\",\r\n"
				+ "        \"19\": \"34372E3130302E3131322E323138\",\r\n"
				+ "        \"121\": \"140501\",\r\n"
				+ "        \"1\": \"00000014\",\r\n"
				+ "        \"122\": \"00000002\",\r\n"
				+ "        \"2\": \"00000014\",\r\n"
				+ "        \"123\": \"1E46\",\r\n"
				+ "        \"3\": \"00000003\",\r\n"
				+ "        \"124\": \"07007F0000000005000000050000000500000005\",\r\n"
				+ "        \"4\": \"00000003\",\r\n"
				+ "        \"5\": \"00000003\",\r\n"
				+ "        \"6\": \"00000003\",\r\n"
				+ "        \"7\": \"00000003\",\r\n"
				+ "        \"128\": \"00008C74\",\r\n"
				+ "        \"129\": \"001F\",\r\n"
				+ "        \"20\": \"43544C5445\",\r\n"
				+ "        \"64\": \"3031323138383838\",\r\n"
				+ "        \"21\": \"63617264\",\r\n"
				+ "        \"65\": \"3031323136363636\",\r\n"
				+ "        \"22\": \"63617264\",\r\n"
				+ "        \"66\": \"\",\r\n"
				+ "        \"23\": \"34372E3130302E3131322E323138\",\r\n"
				+ "        \"67\": \"3031323138383838\",\r\n"
				+ "        \"24\": \"00002268\",\r\n"
				+ "        \"68\": \"3132333435363738393131\",\r\n"
				+ "        \"25\": \"00000000\",\r\n"
				+ "        \"69\": \"00000000\",\r\n"
				+ "        \"26\": \"3131312E3230352E3230322E3737\",\r\n"
				+ "        \"27\": \"00002AF9\",\r\n"
				+ "        \"28\": \"00000000\",\r\n"
				+ "        \"29\": \"3139322E3136382E32302E3230\",\r\n"
				+ "        \"130\": \"0000\",\r\n"
				+ "        \"131\": \"41313233343533\",\r\n"
				+ "        \"132\": \"01\",\r\n"
				+ "        \"256\": \"00000000\",\r\n"
				+ "        \"257\": \"0000\",\r\n"
				+ "        \"258\": \"00000000\",\r\n"
				+ "        \"259\": \"0000\",\r\n"
				+ "        \"70\": \"00000078\",\r\n"
				+ "        \"71\": \"00000E10\",\r\n"
				+ "        \"72\": \"3132333435363738393131\",\r\n"
				+ "        \"73\": \"3132333435363738393131\",\r\n"
				+ "        \"32\": \"00000000\",\r\n"
				+ "        \"33\": \"00000000\",\r\n"
				+ "        \"34\": \"0000000A\",\r\n"
				+ "        \"39\": \"00000078\",\r\n"
				+ "        \"100\": \"00000000\",\r\n"
				+ "        \"144\": \"03\",\r\n"
				+ "        \"101\": \"00000000\",\r\n"
				+ "        \"145\": \"01\",\r\n"
				+ "        \"146\": \"01\",\r\n"
				+ "        \"147\": \"00000001\",\r\n"
				+ "        \"148\": \"01\",\r\n"
				+ "        \"149\": \"00000001\",\r\n"
				+ "        \"80\": \"00000000\",\r\n"
				+ "        \"81\": \"00000000\",\r\n"
				+ "        \"82\": \"00000000\",\r\n"
				+ "        \"83\": \"00000000\",\r\n"
				+ "        \"40\": \"0000000A\",\r\n"
				+ "        \"84\": \"00000000\",\r\n"
				+ "        \"41\": \"0000000F\",\r\n"
				+ "        \"85\": \"0000005A\",\r\n"
				+ "        \"86\": \"0000000A\",\r\n"
				+ "        \"87\": \"00003840\"\r\n"
				+ "    }";
	}
	public static String getListStr() {
		return "[\r\n"
				+ "        {\r\n"
				+ "            \"id\": 1,\r\n"
				+ "            \"paramid\": \"0x0001\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"终端心跳发送间隔，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 2,\r\n"
				+ "            \"paramid\": \"0x0002\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"TCP 消息应答超时时间，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 3,\r\n"
				+ "            \"paramid\": \"0x0003\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"TCP 消息重传次数\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 4,\r\n"
				+ "            \"paramid\": \"0x0004\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"UDP 消息应答超时时间，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 5,\r\n"
				+ "            \"paramid\": \"0x0005\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"UDP 消息重传次数\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 6,\r\n"
				+ "            \"paramid\": \"0x0006\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"SMS 消息应答超时时间，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 7,\r\n"
				+ "            \"paramid\": \"0x0007\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"SMS 消息重传次数\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 8,\r\n"
				+ "            \"paramid\": \"0x0010\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"主服务器 APN，无线通信拨号访问点。若网络制式为 CDMA，则该处为 PPP 拨号号码\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 9,\r\n"
				+ "            \"paramid\": \"0x0011\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"主服务器无线通信拨号用户名 \"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 10,\r\n"
				+ "            \"paramid\": \"0x0012\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"主服务器无线通信拨号密码\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 11,\r\n"
				+ "            \"paramid\": \"0x0013\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"主服务器地址,IP 或域名【IP端口要一起设置】\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 12,\r\n"
				+ "            \"paramid\": \"0x0014\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"备份服务器 APN，无线通信拨号访问点\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 13,\r\n"
				+ "            \"paramid\": \"0x0015\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"备份服务器无线通信拨号用户名\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 14,\r\n"
				+ "            \"paramid\": \"0x0016\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"备份服务器无线通信拨号密码\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 15,\r\n"
				+ "            \"paramid\": \"0x0017\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"备份服务器地址,IP 或域名\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 16,\r\n"
				+ "            \"paramid\": \"0x0018\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"服务器 TCP 端口\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 17,\r\n"
				+ "            \"paramid\": \"0x0019\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"服务器 UDP 端口\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 18,\r\n"
				+ "            \"paramid\": \"0x001A\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"道路运输证 IC 卡认证主服务器 IP 地址或域名\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 19,\r\n"
				+ "            \"paramid\": \"0x001B\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"道路运输证 IC 卡认证主服务器 TCP 端口\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 20,\r\n"
				+ "            \"paramid\": \"0x001C\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"道路运输证 IC 卡认证主服务器 UDP 端口\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 21,\r\n"
				+ "            \"paramid\": \"0x001D\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"道路运输证 IC 卡认证备份服务器 IP 地址或域名，端口同主服务器\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 22,\r\n"
				+ "            \"paramid\": \"0x0020\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"位置汇报策略，0：定时汇报；1：定距汇报；2：定时和定距汇报\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 23,\r\n"
				+ "            \"paramid\": \"0x0021\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"位置汇报方案，0：根据 ACC 状态； 1：根据登录状态和 ACC 状态， 先判断登录状态，若登录再根据 ACC 状态\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 24,\r\n"
				+ "            \"paramid\": \"0x0022\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"驾驶员未登录汇报时间间隔，单位为秒（s），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 25,\r\n"
				+ "            \"paramid\": \"0x0027\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"休眠时汇报时间间隔，单位为秒（s），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 26,\r\n"
				+ "            \"paramid\": \"0x0028\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"紧急报警时汇报时间间隔，单位为秒（s），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 27,\r\n"
				+ "            \"paramid\": \"0x0029\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"缺省时间汇报间隔，单位为秒（s），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 28,\r\n"
				+ "            \"paramid\": \"0x002C\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"缺省距离汇报间隔，单位为米（m），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 29,\r\n"
				+ "            \"paramid\": \"0x002D\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"驾驶员未登录汇报距离间隔，单位为米（m），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 30,\r\n"
				+ "            \"paramid\": \"0x002E\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"休眠时汇报距离间隔，单位为米（m），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 31,\r\n"
				+ "            \"paramid\": \"0x002F\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"紧急报警时汇报距离间隔，单位为米（m），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 32,\r\n"
				+ "            \"paramid\": \"0x0030\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"拐点补传角度，<180\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 33,\r\n"
				+ "            \"paramid\": \"0x0031\",\r\n"
				+ "            \"type\": \"WORD\",\r\n"
				+ "            \"remark\": \"电子围栏半径（非法位移阈值），单位为米\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 34,\r\n"
				+ "            \"paramid\": \"0x0040\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"监控平台电话号码\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 35,\r\n"
				+ "            \"paramid\": \"0x0041\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"复位电话号码，可采用此电话号码拨打终端电话让终端复位\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 36,\r\n"
				+ "            \"paramid\": \"0x0042\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"恢复出厂设置电话号码，可采用此电话号码拨打终端电话让终端恢复 出厂设置\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 37,\r\n"
				+ "            \"paramid\": \"0x0043\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"监控平台 SMS 电话号码\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 38,\r\n"
				+ "            \"paramid\": \"0x0044\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"接收终端SMS 文本报警号码\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 39,\r\n"
				+ "            \"paramid\": \"0x0045\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"终端电话接听策略，0：自动接听；1：ACC ON 时自动接听，OFF 时手 动接听\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 40,\r\n"
				+ "            \"paramid\": \"0x0046\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"每次最长通话时间，单位为秒（s），0 为不允许通话，0xFFFFFFFF 为 不限制\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 41,\r\n"
				+ "            \"paramid\": \"0x0047\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"当月最长通话时间，单位为秒（s），0 为不允许通话，0xFFFFFFFF 为 不限制\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 42,\r\n"
				+ "            \"paramid\": \"0x0048\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"监听电话号码\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 43,\r\n"
				+ "            \"paramid\": \"0x0049\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"监管平台特权短信号码\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 44,\r\n"
				+ "            \"paramid\": \"0x0050\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"报警屏蔽字，与位置信息汇报消息中的报警标志相对应，相应位为 1 则相应报警被屏蔽\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 45,\r\n"
				+ "            \"paramid\": \"0x0051\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"报警发送文本 SMS 开关，与位置信息汇报消息中的报警标志相对应， 相应位为 1 则相应报警时发送文本 SMS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 46,\r\n"
				+ "            \"paramid\": \"0x0052\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"报警拍摄开关，与位置信息汇报消息中的报警标志相对应，相应位为 1 则相应报警时摄像头拍摄\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 47,\r\n"
				+ "            \"paramid\": \"0x0053\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"报警拍摄存储标志，与位置信息汇报消息中的报警标志相对应，相应 位为 1 则对相应报警时拍的照片进行存储，否则实时上传\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 48,\r\n"
				+ "            \"paramid\": \"0x0054\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"关键标志，与位置信息汇报消息中的报警标志相对应，相应位为 1 则 对相应报警为关键报警\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 49,\r\n"
				+ "            \"paramid\": \"0x0055\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"最高速度，单位为公里每小时（km/h）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 50,\r\n"
				+ "            \"paramid\": \"0x0056\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"超速持续时间，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 51,\r\n"
				+ "            \"paramid\": \"0x0057\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"连续驾驶时间门限，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 52,\r\n"
				+ "            \"paramid\": \"0x0058\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"当天累计驾驶时间门限，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 53,\r\n"
				+ "            \"paramid\": \"0x0059\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"最小休息时间，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 54,\r\n"
				+ "            \"paramid\": \"0x005A\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"最长停车时间，单位为秒（s）\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 55,\r\n"
				+ "            \"paramid\": \"0x005B\",\r\n"
				+ "            \"type\": \"WORD\",\r\n"
				+ "            \"remark\": \"超速报警预警差值，单位为 1/10Km/h\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 56,\r\n"
				+ "            \"paramid\": \"0x005C\",\r\n"
				+ "            \"type\": \"WORD\",\r\n"
				+ "            \"remark\": \"疲劳驾驶预警差值，单位为秒（s），>0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 57,\r\n"
				+ "            \"paramid\": \"0x005D\",\r\n"
				+ "            \"type\": \"WORD\",\r\n"
				+ "            \"remark\": \"碰撞报警参数设置:b7-b0： 碰撞时间，单位 4ms；  b15-b8：碰撞加速度，单位 0.1g，设置范围在：0-79 之间，默认为 10。\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 58,\r\n"
				+ "            \"paramid\": \"0x005E\",\r\n"
				+ "            \"type\": \"WORD\",\r\n"
				+ "            \"remark\": \"侧翻报警参数设置：  侧翻角度，单位 1 度，默认为 30 度。\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 59,\r\n"
				+ "            \"paramid\": \"0x0064\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"定时拍照控制，见 表 13\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 60,\r\n"
				+ "            \"paramid\": \"0x0065\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"定距拍照控制，见 表 14\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 61,\r\n"
				+ "            \"paramid\": \"0x0070\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"图像/视频质量，1-10，1 最好\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 62,\r\n"
				+ "            \"paramid\": \"0x0071\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"亮度，0-255\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 63,\r\n"
				+ "            \"paramid\": \"0x0072\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"对比度，0-127\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 64,\r\n"
				+ "            \"paramid\": \"0x0073\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"饱和度，0-127\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 65,\r\n"
				+ "            \"paramid\": \"0x0074\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"色度，0-255\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 66,\r\n"
				+ "            \"paramid\": \"0x0080\",\r\n"
				+ "            \"type\": \"DWORD\",\r\n"
				+ "            \"remark\": \"车辆里程表读数，1/10km\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 67,\r\n"
				+ "            \"paramid\": \"0x0081\",\r\n"
				+ "            \"type\": \"WORD\",\r\n"
				+ "            \"remark\": \"车辆所在的省域 ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 68,\r\n"
				+ "            \"paramid\": \"0x0082\",\r\n"
				+ "            \"type\": \"WORD\",\r\n"
				+ "            \"remark\": \"车辆所在的市域 ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 69,\r\n"
				+ "            \"paramid\": \"0x0083\",\r\n"
				+ "            \"type\": \"STRING\",\r\n"
				+ "            \"remark\": \"公安交通管理部门颁发的机动车号牌\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": 70,\r\n"
				+ "            \"paramid\": \"0x0084\",\r\n"
				+ "            \"type\": \"BYTE\",\r\n"
				+ "            \"remark\": \"车牌颜色，按照 JT/T415-2006 的 5.4.12\"\r\n"
				+ "        }\r\n"
				+ "    ]";
	}
}
